### ISSUE TITLE
Annotation support for places for id

### ISSUE THREAD

**Issue by unpluggedk** [microsoftgraph/msgraph-sdk-ios#10]
For example, using 
-(MSGraphUserRequestBuilder _)users:(NSString_)usersId;
the method, user principal also works in place of userId but isn't described anywhere

**Comment by jasonjoh** [comment]
This project is being archived and replaced with the [Microsoft Graph SDK for ObjC](https://github.com/microsoftgraph/msgraph-sdk-objc). As part of the archival process, we're closing all open issues and pull requests. See #37 for more context.

You can continue to use this library "as-is", but it won't be maintained moving forward. We apologize for any inconvenience.
