### ISSUE TITLE
Incorrect pod file instructions

### ISSUE THREAD

**Issue by GrantMeStrength** [microsoftgraph/msgraph-sdk-ios#12]
Add the following to your Podfile : pod 'MSGraphSDK', '~> 0.10''
- There is an extra '
- pod install fails with "[!] Unable to find a specification for `MSGraphSDK (~> 0.10)`"

**Comment by unpluggedk** [comment]
Thanks, this has been fixed.
That was a typo, and the second error was caused by the updated version of cocoaPods - target is now mandatory, not optional.
