### ISSUE TITLE
I am getting a code = 4 error ? 

### ISSUE THREAD

**Issue by ArEnSc** [microsoftgraph/msgraph-sdk-ios#13]
Error Domain=com.microsoft.graphsdk.autherror Code=4 "(null)"
Error Domain=com.microsoft.graphsdk.autherror Code=4 "(null)"

 NXOAuth2AuthenticationProvider.setClientId("0fddb442-84e2-4b44-add9-088acfaacc4f", scopes: ["https://graph.microsoft.com/Calendars.ReadWrite"])
            NXOAuth2AuthenticationProvider.sharedAuthProvider().loginWithViewController(self.window?.rootViewController) { (error) in
                if (error == nil) {
                    MSGraphClient.setAuthenticationProvider(NXOAuth2AuthenticationProvider.sharedAuthProvider())
                    self.client = MSGraphClient.defaultClient()
                }
                else {
                    print(error.description)
                    print(error.debugDescription)
                }
            }

Can anyone assist me this is not really debuggable on my own there is no description for the error.

**Comment by ArEnSc** [comment]
Error Domain=com.microsoft.graphsdk.autherror Code=3 "(null)"
Error Domain=com.microsoft.graphsdk.autherror Code=3 "(null)"
Okay so I instead received a bad request error.
I registration my application through the app portal.

**Comment by ghost** [comment]
I am geting same error com.microsoft.graphsdk.autherror error 4

**Comment by wesley-dynamicowl** [comment]
I ran into this issue the other day. It took me a while to figure out what was going on (I'm using swift btw).

The error class returned by default is pretty much useless (at least in Swift).  I needed to explicitly cast it to an `NSError`.  After that, I dug around and found `MSAuthErrorType` enum in the `MSAuthConstants` class.

Basically, the codes correspond to one of the errors in that class. Code 3 = auth cancelled, Code 4 means invalid account type. You can get the error code with a call like this:

```
let graphError = MSAuthErrorType(rawValue: error.code)
```

then you can simply run checks like this:

```
switch graphError
case: .authCancelled
    //...
case: .invalidAccountType
    //....
default:
    //....
```

Sorry, that's in Swift. I haven't really dug into ObjC so I don't want to make a horrible attempt at it.

**Comment by ArEnSc** [comment]
So the solution to this problem is a long and involved there is a two stage registration process. http://stackoverflow.com/questions/39796757/microsoft-graph-api-problems-ios-unable-to-complete-request-validation-error here it is good luck guys, it also turns out you can make 2.0 api graph requests once you are authenticated

**Comment by unpluggedk** [comment]
There are 2 registration options, as well as w different api endpoints.

In regards to registration, there is a Azure AD and then there is a Azure AD v2.0.
As for api endpoints, there is v1.0 and beta endpoints.

As for the error above, it has to do with registration, not endpoint issue in terms of apis.
FYI, this current version of the SDK doesn't support hitting the beta endpoints. However, the issue originally posted can be fixed using the right registration.

Hope this helps. If you could supply where the code came from and what permissions you gave the registered app, in terms of registration link, we could provide further assistance.
