### ISSUE TITLE
Ability to set cachePolicy?

### ISSUE THREAD

**Issue by wesley-dynamicowl** [microsoftgraph/msgraph-sdk-ios#14]
Is there anyway to control how requests are cached? 

It looks like the default policy is `cachePolicy:NSURLRequestReloadIgnoringCacheData` in `MSRequest`.

For more context, 

```
    // Apple tries to be smart but they are using the wrong eTag when making requests...
    // so we must disable the caching policy
    NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:url
                                                           cachePolicy:NSURLRequestReloadIgnoringCacheData
                                                       timeoutInterval:60];
```

Pretty frustrating to simply assume that we don't want to use caching. Caching things like user lists and upcoming events is an easy way to add offline support.

**Comment by unpluggedk** [comment]
Thanks for the feedback, you have a valid point. We'll check what we could do.
Meanwhile, you could declare a static property in MSGraphSDK>Extensions>MSGraphClient+DefaultConfigurations, to set/get the policy and have the MSRequest use that value.

You'd probably know how to but let me know if you need help in that 👍 

Thanks

**Comment by jasonjoh** [comment]
This project is being archived and replaced with the [Microsoft Graph SDK for ObjC](https://github.com/microsoftgraph/msgraph-sdk-objc). As part of the archival process, we're closing all open issues and pull requests. See #37 for more context.

You can continue to use this library "as-is", but it won't be maintained moving forward. We apologize for any inconvenience.
