### ISSUE TITLE
Clicking auth screen cancel button return an "Invalid Account Type"

### ISSUE THREAD

**Issue by wesley-dynamicowl** [microsoftgraph/msgraph-sdk-ios#15]
On the authorization screen, when the user clicks the "Cancel" button (circled in image below) within the login web view, the SDK returns an "Invalid Account Type" error. However, when the user clicks the "Cancel" button in the iOS navigation bar, the SDK returns "Auth Cancelled" error.

![image](https://cloud.githubusercontent.com/assets/19351307/19912041/102c08f6-a06e-11e6-9088-d02a0e9289ec.png)

Expected Behavior: Both cancel buttons should return an "Auth Cancelled" error.

**Comment by unpluggedk** [comment]
It does indeed seems like a bug from the authentication provider, we'll check.
Thanks!
