### ISSUE TITLE
Assertion Failure during call of MSGraph.client

### ISSUE THREAD

**Issue by TaralRathod** [microsoftgraph/msgraph-sdk-ios#16]
I have integrated iOS-Graph-SDK with my application I am getting authentication properly but at the time of sending mail when I am calling [MSGraph client] it gives me Exception as "Assertion failure in +[MSGraphClient clientWithConfig:]"  and Showing reason as "reason: 'Invalid parameter not satisfying: config.authenticationProvider'"

where I am missing? as it is working properly for SDK provided by Microsoft
Thanks in advance.

**Comment by unpluggedk** [comment]
have you called [MSGraphClient setAuthenticationProvider:myAuthProvider]?

**Comment by TaralRathod** [comment]
@unpluggedk Yes, I have added that line in viewDidLoad method but after calling that method I am getting this exception of assertion failure

**Comment by unpluggedk** [comment]
Are you setting it before you call the authentication?
Do any other requests work?

**Comment by jasonjoh** [comment]
This project is being archived and replaced with the [Microsoft Graph SDK for ObjC](https://github.com/microsoftgraph/msgraph-sdk-objc). As part of the archival process, we're closing all open issues and pull requests. See #37 for more context.

You can continue to use this library "as-is", but it won't be maintained moving forward. We apologize for any inconvenience.
