### ISSUE TITLE
How to use response_type

### ISSUE THREAD

**Issue by nawar** [microsoftgraph/msgraph-sdk-ios#18]
I'm trying to implement a delegated flow scenario to act on behalf of the user with a backend application and I believe the way to do that is getting an authorization code that I can use later on to request an Access and Refresh tokens. What's the best way to specify that with this SDK?

**Comment by dpim** [comment]
For work+school accounts, you can use [ADAL for iOS](https://github.com/AzureAD/azure-activedirectory-library-for-objc) to authorize a user
