### ISSUE TITLE
Missing "create upload session" in MSGraphDriveItemRequestBuilder

### ISSUE THREAD

**Issue by tobihagemann** [microsoftgraph/msgraph-sdk-ios#20]
I'd like to upload large files using "resumable upload": https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/item_createuploadsession

However, it looks like that `createUploadSession` is missing in this SDK. Or did I miss something?

Interestingly enough, there is a `MSGraphUploadSession` which can be used as the response object for the `createUploadSession` POST request. But it's not used anywhere.

**Comment by caitlinrussell** [comment]
This is a custom feature that is not automatically created in the iOS library generation process. We have done similar work in other languages and will need to implement this here as well. Thanks for finding this.

**Comment by mihaierosx2** [comment]
@cbales  Any ETA for this one?

**Comment by MIchaelMainer** [comment]
@mihaierosx2 We don't have an ETA on this just yet. Thank you for letting us know your interest in this feature.

**Comment by edm60** [comment]
I too need to be able to upload large files - is there at least a work-around available?

**Comment by mihaierosx2** [comment]
@edm60 I ended up by using something like this:

```
MSGraphDriveItemContentRequest *request;
[request uploadFromData:fileData completion:^(MSGraphDriveItem *response, NSError *error) {
   // handling
}];
```

**Comment by edm60** [comment]
@mihaierosx2 Thanks I have this working but it gives an error 413 for large files

**Comment by tobihagemann** [comment]
It's quite the similar situation with the old OneDrive SDK and the solution is similar as well (basically, you have to do it yourself): https://github.com/OneDrive/onedrive-sdk-ios/issues/122#issuecomment-246048492

**Comment by edm60** [comment]
@tobihagemann Any chance of a snippet of code using the new MSGraph API? Anything would be a help - perhaps a translation of:

`ODClient *client = ...;

// create an upload session: https://dev.onedrive.com/items/upload_large_files.htm#create-an-upload-session
ODChunkedUploadSessionDescriptor *item = [[ODChunkedUploadSessionDescriptor alloc] init];
item.name = @"largefile.dat"; // not sure, but it looks like you have to fill in the filename
ODURLSessionDataTask *task = [[[[client root] createSessionWithItem:item] request] executeWithCompletion:^(ODUploadSession *response, NSError *error) {
    // upload fragment: https://dev.onedrive.com/items/upload_large_files.htm#upload-fragments
}];`

**Comment by jthake** [comment]
I have this working with fragments using the MSAL library and no SDK. 
https://github.com/jthake/OneDrive-iOS-Swift-LargeFileUploader
The guts of it is here
https://github.com/jthake/OneDrive-iOS-Swift-LargeFileUploader/blob/master/MSALiOS/OneDriveManager.swift#L122

It needs some work, as I have a sleep in there to overcoming some race conditions of fragments not uploading in order.

**Comment by jasonjoh** [comment]
This project is being archived and replaced with the [Microsoft Graph SDK for ObjC](https://github.com/microsoftgraph/msgraph-sdk-objc). As part of the archival process, we're closing all open issues and pull requests. See #37 for more context.

You can continue to use this library "as-is", but it won't be maintained moving forward. We apologize for any inconvenience.
