### ISSUE TITLE
One time login using Client object is not working

### ISSUE THREAD

**Issue by Manohar-Stark** [microsoftgraph/msgraph-sdk-ios#21]
I am trying sync google calendar and outlook calendar sync for our app. Google sync is working fine. I am facing issues with outlook sync.

Here is the flow , I login into my app and navigate to the page containing two buttons, one for google sync and the other for outlook sync. Inside the click events, I have called the services to sync respective calendars. I have options to logout again using another click event.

First time, I need to login using outlook/google account to sync. On success, control is transferred to different page. Google sync is working fine. For outlook I have used MSGraph SDK authentication to set provider authentication. Using the MSGraphClient object, i making request against the services. I have followed ,

https://github.com/microsoftgraph/msgraph-sdk-ios

After this I am making get and set events service requests to sync my app account.This is working fine too.

**The Problem is when I exit my app, and login again, the outlook sync is gone.So I have to login outlook account to sync again. Please advise a way to keep the account logged in , until and unless I remove the synced account.**

**Comment by MIchaelMainer** [comment]
You'll want to cache a refresh token so that when you log back into your app, the app submits the refresh token for a new access token. Take a look at this sample as the ReadMe states that it shows how to get a refresh token (note that I'm not familiar with this iOS scenario).
https://github.com/Azure-Samples/active-directory-ios-swift-native-v2

**Comment by pvn2266** [comment]
Hi
Can you please tell me how keychain sharing is working.
I need to use keychain sharing to enable SSO - single sign on for my apps. However as per "loginSilent" method 
the sdk checks " NSString *identifier = [self lastSuccessfulLoginIdentifier];
" 
which is in NSUserDefaults (locally). Thus the identifier will be nil always for first time login even when the other app is already logged in..
