### ISSUE TITLE
when will planner and task be available

### ISSUE THREAD

**Issue by paresh-navadiya** [microsoftgraph/msgraph-sdk-ios#22]
Need it urgently to get planner and task integrated in project. According to my requirement, I need both of them to be integrated in project. Can you just let me know when it will be done.

**Comment by MIchaelMainer** [comment]
I don't have a time frame for when these features will be available in this client library. I suggest that you use your favorite HTTP stack and make the calls for planner tasks outside of this client library.

**Comment by jasonjoh** [comment]
This project is being archived and replaced with the [Microsoft Graph SDK for ObjC](https://github.com/microsoftgraph/msgraph-sdk-objc). As part of the archival process, we're closing all open issues and pull requests. See #37 for more context.

You can continue to use this library "as-is", but it won't be maintained moving forward. We apologize for any inconvenience.
