### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by beseder42** [microsoftgraph/msgraph-sdk-ios#23]
It would be great if the installation via Carthage is supported!

**Comment by ghost** [comment]
Yes please.

**Comment by jasonjoh** [comment]
This project is being archived and replaced with the [Microsoft Graph SDK for ObjC](https://github.com/microsoftgraph/msgraph-sdk-objc). As part of the archival process, we're closing all open issues and pull requests. See #37 for more context.

You can continue to use this library "as-is", but it won't be maintained moving forward. We apologize for any inconvenience.
