### ISSUE TITLE
how can I sign in simultaneously with different accounts

### ISSUE THREAD

**Issue by deco1515** [microsoftgraph/msgraph-sdk-ios#24]
when I sign in with different accounts, it shows "You're already signed in". 
I can remain the old account or sign out the old account first.
Is there any solutions?

**Comment by caitlinrussell** [comment]
Login and session caching is not part of this library right now.  You can log a feature request with the authentication provider you are using ([msgraph-sdk-ios-nxoauth2-adapter](https://github.com/microsoftgraph/msgraph-sdk-ios-nxoauth2-adapter) or [microsoft-authentication-library-for-objc](https://github.com/AzureAD/microsoft-authentication-library-for-objc), possibly?)
