### ISSUE TITLE
SSO not working

### ISSUE THREAD

**Issue by pvn2266** [microsoftgraph/msgraph-sdk-ios#25]
Keychain sharing shares logged in account in the sdk.

I need to use keychain sharing to enable SSO - single sign on for my apps. 
However as per "loginSilent" method 
the sdk checks-
 " NSString *identifier = [self lastSuccessfulLoginIdentifier];" 
which is in NSUserDefaults (locally). Thus the identifier will be nil always for first time login even when the other app is already logged in..

hence it will always through a webview login page for the first time.

**Comment by MIchaelMainer** [comment]
Can you point me at where you're seeing this?

Did you mean to ask this question in the auth library repo?
https://github.com/AzureAD/microsoft-authentication-library-for-objc

**Comment by pvn2266** [comment]
I am not using Azure library. I am using Microsoft graph library for this.
https://github.com/microsoftgraph/msgraph-sdk-ios

However i just figured out some interesting way for SSO. Use Microsoft Authenticator app

**Comment by caitlinrussell** [comment]
I believe you are asking a question about the auth adapter: [MSAuthenticationProvider implementation for MSGraph SDK](https://github.com/microsoftgraph/msgraph-sdk-ios-nxoauth2-adapter). I believe your question has not been asked yet on this repo, so you will have to open a new question.
