### ISSUE TITLE
Logging into German-hosted OneDrive servers fails.

### ISSUE THREAD

**Issue by Alex-C-Eltima** [microsoftgraph/msgraph-sdk-ios#29]
Could you please assist or clarify, it seems your SDK works only with US-hosted OneDrive servers (office.com). One of our German users has account under portal.office.de server, hosted by T-Systems in German data center. And it looks like authentication is searching for his credentials on US servers, when he tries to login from Germany.

**Comment by caitlinrussell** [comment]
Is this an issue with the auth adapter: [msgraph-sdk-ios-nxoauth2-adapter]( https://github.com/microsoftgraph/msgraph-sdk-ios-nxoauth2-adapter)? Or are you using MSAL for iOS: [microsoft-authentication-library-for-objc](https://github.com/AzureAD/microsoft-authentication-library-for-objc)? The SDK does not directly handle authentication.

**Comment by Alex-C-Eltima** [comment]
Yes, we are using https://github.com/microsoftgraph/msgraph-sdk-ios-nxoauth2-adapter Thank you for pointing me to the correct location. Will ask there.
