### ISSUE TITLE
Auth not work with secondary login

### ISSUE THREAD

**Issue by narlei** [microsoftgraph/msgraph-sdk-ios#30]
In a business account, my customer has a secondary login, with a popUp but not work with this SDK, the popUp is not presented and the login freeze.

**Comment by caitlinrussell** [comment]
Is this an issue with the auth adapter: [msgraph-sdk-ios-nxoauth2-adapter](https://github.com/microsoftgraph/msgraph-sdk-ios-nxoauth2-adapter)? Or are you using MSAL for iOS: [microsoft-authentication-library-for-objc](https://github.com/AzureAD/microsoft-authentication-library-for-objc)? The SDK does not directly handle authentication.

**Comment by igoMobile** [comment]
We experience also problems with signing in with a business account in Xcode 9 (latest iOS SDK). The error is:

`CredStore - performQuery - Error copying matching creds. Error=-25300, query={ class = inet; "m_Limit" = "m_LimitAll"; ptcl = htps; "r_Attributes" = 1; sdmn = "*** valid enterprise adf URL ***"; srvr = "*** valid enterprise adf URL ***"; sync = syna; }`

and the login window freezes with a message "Taking you to your organizations's sign-in page". We use msgraph-sdk-ios-nxoauth2-adapter to handle authentication. But this project seems to be not developed in the last 2 years. Is there a chance, the error will be fixed? Thanks!

**Comment by caitlinrussell** [comment]
Issue: https://github.com/microsoftgraph/msgraph-sdk-ios-nxoauth2-adapter/issues/12

**Comment by pedro-bread** [comment]
We're experiencing the same issue here. A bit frustrating. We finally bit the bullet and used this SDK against all the warning signs and its abandoned development. Shame on us
