### ISSUE TITLE
Manual Setup

### ISSUE THREAD

**Issue by ncperry** [microsoftgraph/msgraph-sdk-ios#32]
We don't use CocoaPods on our project and would like to incorporate your SDK manually. We can clone the repo and add the the MSGraphSDK.xcodeproj to our own project. We then successfully compiled MSGraphSDK.framework using the MSGraphSDK target. We then embedded and linked the framework into our own project. All of this we did successfully and our project was building.

We then tried to '#import <MSGraphSDK/MSGraphSDK.h>` and we got the following bugs: 

``` 
MSURLSessionManager.h file not found
Could not build module MSGraphSDK
Failed to emit precompiled header ... 
```

Is there any way for us to work around this?

**Comment by jasonjoh** [comment]
This project is being archived and replaced with the [Microsoft Graph SDK for ObjC](https://github.com/microsoftgraph/msgraph-sdk-objc). As part of the archival process, we're closing all open issues and pull requests. See #37 for more context.

You can continue to use this library "as-is", but it won't be maintained moving forward. We apologize for any inconvenience.
