### ISSUE TITLE
How can I use Microsoft Graph SDK for Outlook login?

### ISSUE THREAD

**Issue by derpoliuk** [microsoftgraph/msgraph-sdk-ios#33]
https://github.com/OfficeDev/Outlook-SDK-iOS states that it is deprecated and one should use Microsoft Graph SDK. 

As far as I understand Graph SDK uses `https://graph.microsoft.com/v1.0/` APIs for login and accessing `/me` info. 

How can I use Graph SDK to access `https://outlook.office.com/api/v2.0` resources?

**Comment by MIchaelMainer** [comment]
The Microsoft Graph iOS SDK doesn't have any built in authentication mechanism. It will take an access token once you've acquired it. Please take a look at https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-devquickstarts-ios.

The Graph API sits on top of the Outlook API. Most of the functionality is already surfaced in the Graph API.

**Comment by MIchaelMainer** [comment]
https://github.com/microsoftgraph?utf8=%E2%9C%93&q=ios&type=&language=

**Comment by derpoliuk** [comment]
@MIchaelMainer thank you for very quick response! I didn't explain in details what I've done and what I'm trying to achieve.

My end goal is to login user with Office 365 account and get:
* refresh token
* user details
* id token (`id_token` as described in [Azure Active Directory (AAD) endpoint documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-protocols-oauth-code#successful-response-1))

Using sample app I was able to login user, get refresh token and user details (via `[[[[MSGraphClient client] me] request] getWithCompletion:...]`) but I can't find `id_token` anywhere.

Also Android version of the app I'm working on is using `https://outlook.office.com/api/v2.0` as a base URL for SDK and I'm trying to change it also in iOS app from `https://graph.microsoft.com/v1.0/`.

**Comment by MIchaelMainer** [comment]
This is an authorization question. Can you please post to StackOverflow with the [AzureAD] tag? I don't know why you aren't getting an `id_token`.

**Comment by derpoliuk** [comment]
@MIchaelMainer I did figure out `id_token` part. But I'm still having issue setting URL I want to use in SDK.

By default SDK uses `https://graph.microsoft.com/v1.0/` URL for all methods and I'm trying to make SDK use `https://outlook.office.com/api/v2.0` as URL for all requests.

**Comment by MIchaelMainer** [comment]
This client library is not expected to work against the Outlook endpoint. The Outlook endpoint has been deemphasized in favor of the Graph endpoint.

**Comment by derpoliuk** [comment]
@MIchaelMainer thanks for response! 

I figured out today that I don't need to use `/me` API to get user name and email: I can parse `id_token` obtained from OAuth (as described in [this SO answer](https://stackoverflow.com/a/41565121/1226304)).

Also in [this SO answer](https://stackoverflow.com/a/49500199/1226304) described how to get `id_token`.
