### ISSUE TITLE
SFSafariViewController support?

### ISSUE THREAD

**Issue by derpoliuk** [microsoftgraph/msgraph-sdk-ios#35]
Is there a way to use `SFSafariViewController` for login, like Google or Facebook are doing for login?

**Comment by MIchaelMainer** [comment]
Thank you for your question about the Microsoft Graph. Please post your questions to StackOverflow with the microsoftgraph tag. After you've posted your question on StackOverflow, please provide a link here back to your post. That way, the question will be found by more people -- plus it gives back to the dev community on StackOverflow. 

Make sure you include the following information in your post on StackOverflow:
* What you've tried, your repro steps
* A trace of both the request and response
* Any error messages
* Any settings

**Comment by derpoliuk** [comment]
@MIchaelMainer thank you for response.

I don't think that SO is the best place for this question because it's more "how SDK works under-the-hood" question, not "how to use SDK" question though I framed my question like that. Sorry for that, let me reframe it:

I did try searching for `SFSafariViewController` in the SDK and didn't find any. I only find `UIWebView`.

So my question is: will there be support of `SFSafariViewController` for login instead of `UIWebView`? This will allow users to use AutoFill info for login.

**Comment by MIchaelMainer** [comment]
Thank you for your clarification. This is not currently planned. I will reopen this and tag this as a feature request.

**Comment by derpoliuk** [comment]
@MIchaelMainer thanks!

**Comment by jilaiyuan** [comment]
I also need this feature! Thanks.

**Comment by jasonjoh** [comment]
This project is being archived and replaced with the [Microsoft Graph SDK for ObjC](https://github.com/microsoftgraph/msgraph-sdk-objc). As part of the archival process, we're closing all open issues and pull requests. See #37 for more context.

You can continue to use this library "as-is", but it won't be maintained moving forward. We apologize for any inconvenience.
