### ISSUE TITLE
How to upload larger files more than 4MB using msgraph api from iOS custom app to Sharepoint shared folder.

### ISSUE THREAD

**Issue by ThameemAnsari** [microsoftgraph/msgraph-sdk-ios#36]
Is there any way to upload larger files either photos/videos more than 4MB using MSGraph API from customized iOS application to sharepoint shared document folder. Can you please provide related API rest service or code base to send larger videos or photos from iOS application using MSGRAPH API.

**Comment by darrelmiller** [comment]
@ThameemAnsari You can upload large files by splitting them into "ranges" of bytes and using the Content-Range header to indicate which range you are sending.  Here is an [article](https://developer.microsoft.com/en-us/office/blogs/onedrive-webhooks-and-large-uploads-with-microsoft-graph/) that discusses the feature and some [docs](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession).

We are working towards developing Task classes in our SDKs that will encapsulate the set of requests needed to upload a file, but we are still a fair way out from getting an iOS implementation in the box.

**Comment by jasonjoh** [comment]
This project is being archived and replaced with the [Microsoft Graph SDK for ObjC](https://github.com/microsoftgraph/msgraph-sdk-objc). As part of the archival process, we're closing all open issues and pull requests. See #37 for more context.

You can continue to use this library "as-is", but it won't be maintained moving forward. We apologize for any inconvenience.
