### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by tbeech** [microsoftgraph/msgraph-sdk-ios#37]
It's been a while since there has been any activity on this repo. Is this project still maintained? Looking to integrate with MS Graph API for OneDrive.

**Comment by darrelmiller** [comment]
@tbeech Yes, unfortunately our outward appearance has not reflected the flurry of activity that has been going on.  We have just recently built a team that will be dedicated to improving the SDKs and other developer tooling on the Graph.  I am the new (as of two weeks) PM responsible for the SDKs.  

We are doing work on a new Objective-c SDK that will be built with a standardized component architecture that we hope to apply across all of our languages.  This will hopefully provide the flexibility and ease of use that users have been requesting.

This current SDK is provided as-is and some of the code may make it into the new objective-c SDK, but this is not where are current efforts are being expended.

**Comment by tbeech** [comment]
@darrelmiller Thank you for the response. Do you have a rough estimate as to when we might start seeing the new SDKs? 6 months to year?

**Comment by darrelmiller** [comment]
@tbeech You should see some of the architectural changes appearing in the SDKs within the next few weeks.  Most of the SDKs will adopt the architecture changes incrementally.  The Objective-c one is a bit different, and I don't have any firm timeline to share at this point, but I expect we will be previewing it within a few months.

**Comment by jasonjoh** [comment]
This project is being archived and replaced with the [Microsoft Graph SDK for ObjC](https://github.com/microsoftgraph/msgraph-sdk-objc). As part of the archival process, we're closing all open issues and pull requests.

You can continue to use this library "as-is", but it won't be maintained moving forward. We apologize for any inconvenience.
