### ISSUE TITLE
OneDrive for Business Azure/O365 Subscription Required?

### ISSUE THREAD

**Issue by mmcguill** [microsoftgraph/msgraph-sdk-ios#38]
Hi, 

I'd like to allow users of my app to integrate with their OneDrive for Business drives. I've already integrated against OneDrive Personal, and that is working well, but unfortunately OneDrive for Business is a whole different kettle of fish...

What I'd like to know before I commit much time/resources is if my app will work if I don't have a paid subscription for Office365/Azure? I am currently using a trial to do some early testing, but this will obviously expire. I have no need personally for an Office365/Azure subscription, but I'd like to allow OneDrive for Business users access their own drives through the app. 

As a developer, do I need to pay so that they can access their work/school drives? Very hard to find clear info on this.

Thanks!

**Comment by jasonjoh** [comment]
This project is being archived and replaced with the [Microsoft Graph SDK for ObjC](https://github.com/microsoftgraph/msgraph-sdk-objc). As part of the archival process, we're closing all open issues and pull requests. See #37 for more context.

You can continue to use this library "as-is", but it won't be maintained moving forward. We apologize for any inconvenience.
