### ISSUE TITLE
Login in Fail. You need to use Safari or Intune Managed Browser

### ISSUE THREAD

**Issue by youlianqi** [microsoftgraph/msgraph-sdk-ios#39]
Get an error. "You can't get there from here.  You cannot access the resource from this browser on your device. You need to use Safari or Intune Managed Browser"

**Comment by youlianqi** [comment]
SSO login in.

**Comment by jasonjoh** [comment]
This project is being archived and replaced with the [Microsoft Graph SDK for ObjC](https://github.com/microsoftgraph/msgraph-sdk-objc). As part of the archival process, we're closing all open issues and pull requests. See #37 for more context.

You can continue to use this library "as-is", but it won't be maintained moving forward. We apologize for any inconvenience.
